name: Parallel Cypress Tests

on:
  pull_request:
    branches:
    - develop
    - version-12-hotfix
    - version-11-hotfix

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Redis
        uses: shogo82148/actions-setup-redis@v1

      - name: Install Mariadb
        uses: getong/mariadb-action@v1.1

      - name: before_install
        run: |
          wget -O /tmp/wkhtmltox.tar.xz https://github.com/frappe/wkhtmltopdf/raw/master/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
          tar -xf /tmp/wkhtmltox.tar.xz -C /tmp
          sudo mv /tmp/wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
          sudo chmod o+x /usr/local/bin/wkhtmltopdf
          sudo apt-get install libcups2-dev

      - name: install bench
        run: |
          cd $HOME
          pip install frappe-bench

      - name: init bench
        run: |
          echo $HOME
          cd $HOME
          ls -l $GITHUB_WORKSPACE
          bench init frappe-bench --skip-assets --python $(which python) --frappe-path $GITHUB_WORKSPACE

          mkdir $HOME/frappe-bench/sites/test_site
          cp $GITHUB_WORKSPACE/.travis/consumer_db/mariadb.json $HOME/frappe-bench/sites/test_site/site_config.json

      - name: setup database
        run: |
          /etc/init.d/mysql start
          mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'";
          mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'";

          mysql -u root -e "CREATE DATABASE test_frappe_consumer";
          mysql -u root -e "CREATE USER 'test_frappe_consumer'@'localhost' IDENTIFIED BY 'test_frappe_consumer'";
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe_consumer\`.* TO 'test_frappe_consumer'@'localhost'";

          mysql -u root -e "CREATE DATABASE test_frappe_producer";
          mysql -u root -e "CREATE USER 'test_frappe_producer'@'localhost' IDENTIFIED BY 'test_frappe_producer'";
          mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe_producer\`.* TO 'test_frappe_producer'@'localhost'";

          mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'";
          mysql -u root -e "FLUSH PRIVILEGES";

      - name: start bench
        run: |
          cd $HOME/frappe-bench
          sed -i 's/watch:/# watch:/g' Procfile
          sed -i 's/schedule:/# schedule:/g' Procfile
          sed -i 's/socketio:/# socketio:/g' Procfile;
          sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile;
          bench start &

      - name: run test
        run: |
          cd $HOME/frappe-bench
          bench --site test_site reinstall --yes
          bench setup requirements --node;
          bench build --app frappe
          bench --site test_site execute frappe.utils.install.complete_setup_wizard
          bench --site test_site run-ui-tests frappe --headless --parallel
